In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [4]:
df.head()

PATIENT  AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
0    Jacob Larsen   83             1               1            2   
1    Allison Hill   30             2               0            3   
2  Susan Sandoval   64             4               3            4   
3   Melissa Smith   26             4               4            1   

   COAGULATION  HEPATIC  RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  \
0            4        1      4    2     2                  6                2   
1            2        4      1    4     2                  7                2   
2            3        4      0    2     2                  6                2   
3            0        0      2    2     2                  3                2   

   SCORE_SOFA  CLASSIFICATION  
0          13               1  
1          12               2  
2          18               3  
3          11               4

In [5]:
df.describe()


AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  \
count   4.000000          4.00        4.000000     4.000000     4.000000   
mean   50.750000          2.75        2.000000     2.500000     2.250000   
std    27.439327          1.50        1.825742     1.290994     1.707825   
min    26.000000          1.00        0.000000     1.000000     0.000000   
25%    29.000000          1.75        0.750000     1.750000     1.500000   
50%    47.000000          3.00        2.000000     2.500000     2.500000   
75%    68.750000          4.00        3.250000     3.250000     3.250000   
max    83.000000          4.00        4.000000     4.000000     4.000000   

        HEPATIC     RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  \
count  4.000000  4.000000  4.0   4.0           4.000000              4.0   
mean   2.250000  1.750000  2.5   2.0           5.500000              2.0   
std    2.061553  1.707825  1.0   0.0           1.732051              0.0   
min    0.000000  0.000000  2.0   2.0           3.000000              2.0   
25%    0.750000  0.750000  2.0   2.0           5.250000              2.0   
50%    2.500000  1.500000  2.0   2.0           6.000000              2.0   
75%    4.000000  2.500000  2.5   2.0           6.250000              2.0   
max    4.000000  4.000000  4.0   2.0           7.000000              2.0   

       SCORE_SOFA  CLASSIFICATION  
count    4.000000        4.000000  
mean    13.500000        2.500000  
std      3.109126        1.290994  
min     11.000000        1.000000  
25%     11.750000        1.750000  
50%     12.500000        2.500000  
75%     14.250000        3.250000  
max     18.000000        4.000000

In [6]:
df['AGE'].value_counts()

83    1
30    1
64    1
26    1
Name: AGE, dtype: int64

In [7]:
# Shape of Data
df.shape

(4, 14)

In [8]:
# drop some colums we donot need like dates and id
df.drop(columns={'PATIENT'},axis=1,inplace=True)
#df.shape

In [9]:
df.shape

(4, 13)

In [10]:
df['NEUROLOGICAL'].value_counts()

4    2
1    1
2    1
Name: NEUROLOGICAL, dtype: int64

In [11]:
df['CARDIOVASCULAR'].value_counts()

1    1
0    1
3    1
4    1
Name: CARDIOVASCULAR, dtype: int64

In [12]:
df['RESPIRATORY'].value_counts()

2    1
3    1
4    1
1    1
Name: RESPIRATORY, dtype: int64

In [13]:
df['COAGULATION'].value_counts()

4    1
2    1
3    1
0    1
Name: COAGULATION, dtype: int64

In [14]:
df['HEPATIC'].value_counts()

4    2
1    1
0    1
Name: HEPATIC, dtype: int64

In [15]:
df['RENAL'].value_counts()

4    1
1    1
0    1
2    1
Name: RENAL, dtype: int64

In [16]:
df['ICC'].value_counts()


2    3
4    1
Name: ICC, dtype: int64

In [17]:
df['ECOG'].value_counts()

2    4
Name: ECOG, dtype: int64

In [18]:
df['SCORE_SOFA'].value_counts()

13    1
12    1
18    1
11    1
Name: SCORE_SOFA, dtype: int64

In [19]:
df['SCORE_FRAGILITY'].value_counts()

2    4
Name: SCORE_FRAGILITY, dtype: int64

In [20]:
# CHECK  NULL Values
df.isnull().sum()

AGE                  0
NEUROLOGICAL         0
CARDIOVASCULAR       0
RESPIRATORY          0
COAGULATION          0
HEPATIC              0
RENAL                0
ICC                  0
ECOG                 0
SCORE_MINOR_TOTAL    0
SCORE_FRAGILITY      0
SCORE_SOFA           0
CLASSIFICATION       0
dtype: int64

In [21]:
df['CLASSIFICATION'].value_counts()

1    1
2    1
3    1
4    1
Name: CLASSIFICATION, dtype: int64

In [22]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR', 'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_MINOR_TOTAL', 'SCORE_FRAGILITY', 'SCORE_SOFA']]
print(X)

   AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  HEPATIC  \
0   83             1               1            2            4        1   
1   30             2               0            3            2        4   
2   64             4               3            4            3        4   
3   26             4               4            1            0        0   

   RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  SCORE_SOFA  
0      4    2     2                  6                2          13  
1      1    4     2                  7                2          12  
2      0    2     2                  6                2          18  
3      2    2     2                  3                2          11  


In [23]:
df.shape

(4, 13)

In [24]:
df['CLASSIFICATION'].replace([1,2,3],[1,0,2],inplace=True)
df['CLASSIFICATION'].value_counts().to_frame() 

CLASSIFICATION
1               1
0               1
2               1
4               1

In [25]:

y = df['CLASSIFICATION']
print(y)
y.shape

0    1
1    0
2    2
3    4
Name: CLASSIFICATION, dtype: int64


(4,)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [27]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [28]:
# instance of model
treeModel = DecisionTreeClassifier()

In [29]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [30]:
predTree = treeModel.predict(x_test)

In [31]:
print(predTree)

[1]


In [32]:
from sklearn.metrics import accuracy_score

In [33]:
score = accuracy_score(y_test, predTree)

In [34]:
print(score)

0.0


In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [37]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [38]:
ranForestPred = ranModel.predict(x_test)

In [39]:
ranForestPred

array([4], dtype=int64)

In [40]:
ranModel.score(x_test, y_test)

1.0

In [41]:
ranModel

RandomForestClassifier(n_estimators=200)

In [42]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [43]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [44]:
model = pd.read_pickle('Model_MDS.pickle')

In [45]:
result = model.predict([[54, 4, 4, 2, 4, 1, 1, 4, 4, 29, 4,12]])
result

d:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [46]:
result

array([4], dtype=int64)

In [47]:
#import pickle as plk

In [48]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [49]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)