In [1]:
import pandas as pd
import numpy as np

In [25]:
from sklearn.model_selection import train_test_split
from sklearn import tree

In [3]:

file = pd.read_csv("data_generate.csv")
print("\nOriginal file:") 
print(file) 
headerList = ['patients', 'age_1', 'neuro_1', 'cardi_1', 'respi_1', 'coagu_1', 'hepat_1', 'renal_1', 'icc_1', 'ecog_1', 'amib_total_1',
                          'age_2', 'neuro_2', 'cardi_2', 'respi_2', 'coagu_2', 'hepat_2', 'renal_2', 'icc_2', 'ecog_2', 'amib_total_2','decisao']

file.to_csv("data_Values_Patient.csv", header=headerList, index=False) 
file2 = pd.read_csv("data_Values_Patient.csv") 
print('\nModified file:')
print(file2) 


Original file:
        71_6_vs_71_6  82  1  4  4.1  1.1  3  1.2  0  13  ...  1.3  4.2  4.3  \
0        71_6_vs_7_2  82  1  4    4    1  3    1  0  13  ...    3    2    4   
1       71_6_vs_42_8  82  1  4    4    1  3    1  0  13  ...    1    1    1   
2        71_6_vs_8_1  82  1  4    4    1  3    1  0  13  ...    1    4    4   
3       71_6_vs_75_7  82  1  4    4    1  3    1  0  13  ...    3    3    0   
4       71_6_vs_11_4  82  1  4    4    1  3    1  0  13  ...    2    2    3   
...              ...  .. .. ..  ...  ... ..  ... ..  ..  ...  ...  ...  ...   
999994  22_0_vs_99_9  82  2  1    2    4  0    3  3   9  ...    3    0    3   
999995  22_0_vs_71_0  82  2  1    2    4  0    3  3   9  ...    4    4    4   
999996  22_0_vs_42_6  82  2  1    2    4  0    3  3   9  ...    1    2    0   
999997  22_0_vs_16_1  82  2  1    2    4  0    3  3   9  ...    0    2    1   
999998  22_0_vs_22_0  82  2  1    2    4  0    3  3   9  ...    2    1    2   

        1.4  3.2  1.5  0.1  13.1  3

In [4]:
# read Data
df = pd.read_csv('data_Values_Patient.csv')

In [5]:
df.head()

patients  age_1  neuro_1  cardi_1  respi_1  coagu_1  hepat_1  renal_1  \
0   71_6_vs_7_2     82        1        4        4        1        3        1   
1  71_6_vs_42_8     82        1        4        4        1        3        1   
2   71_6_vs_8_1     82        1        4        4        1        3        1   
3  71_6_vs_75_7     82        1        4        4        1        3        1   
4  71_6_vs_11_4     82        1        4        4        1        3        1   

   icc_1  ecog_1  ...  neuro_2  cardi_2  respi_2  coagu_2  hepat_2  renal_2  \
0      0      13  ...        3        2        4        2        0        3   
1      0      13  ...        1        1        1        2        2        0   
2      0      13  ...        1        4        4        0        4        2   
3      0      13  ...        3        3        0        1        0        3   
4      0      13  ...        2        2        3        0        3        3   

   icc_2  ecog_2  amib_total_2  decisao  
0      0      11             2        2  
1      3       7             4        1  
2      0      13             3        0  
3      3       7             4        1  
4      0      10             2        2  

[5 rows x 22 columns]

In [6]:
df.describe()


age_1        neuro_1        cardi_1        respi_1  \
count  999999.000000  999999.000000  999999.000000  999999.000000   
mean       56.781975       2.006001       2.011998       2.101998   
std        27.594988       1.401416       1.399949       1.384773   
min        20.000000       0.000000       0.000000       0.000000   
25%        25.000000       1.000000       1.000000       1.000000   
50%        72.000000       2.000000       2.000000       2.000000   
75%        84.000000       3.000000       3.000000       3.000000   
max        85.000000       4.000000       4.000000       4.000000   

             coagu_1        hepat_1        renal_1          icc_1  \
count  999999.000000  999999.000000  999999.000000  999999.000000   
mean        2.102001       2.067999       2.038001       1.320001   
std         1.390539       1.411871       1.436857       1.489162   
min         0.000000       0.000000       0.000000       0.000000   
25%         1.000000       1.000000       1.000000       0.000000   
50%         2.000000       2.000000       2.000000       0.000000   
75%         3.000000       3.000000       3.000000       3.000000   
max         4.000000       4.000000       4.000000       3.000000   

              ecog_1   amib_total_1  ...        neuro_2        cardi_2  \
count  999999.000000  999999.000000  ...  999999.000000  999999.000000   
mean       10.289997       3.450000  ...       2.006001       2.011998   
std         2.070242       1.098864  ...       1.401416       1.399949   
min         5.000000       2.000000  ...       0.000000       0.000000   
25%         9.000000       3.000000  ...       1.000000       1.000000   
50%        10.000000       3.000000  ...       2.000000       2.000000   
75%        12.000000       4.000000  ...       3.000000       3.000000   
max        14.000000       6.000000  ...       4.000000       4.000000   

             respi_2        coagu_2        hepat_2        renal_2  \
count  999999.000000  999999.000000  999999.000000  999999.000000   
mean        2.101998       2.102001       2.067999       2.038001   
std         1.384773       1.390539       1.411871       1.436857   
min         0.000000       0.000000       0.000000       0.000000   
25%         1.000000       1.000000       1.000000       1.000000   
50%         2.000000       2.000000       2.000000       2.000000   
75%         3.000000       3.000000       3.000000       3.000000   
max         4.000000       4.000000       4.000000       4.000000   

               icc_2         ecog_2   amib_total_2        decisao  
count  999999.000000  999999.000000  999999.000000  999999.000000  
mean        1.320001      10.289997       3.450000       1.339201  
std         1.489162       2.070242       1.098864       0.662225  
min         0.000000       5.000000       2.000000       0.000000  
25%         0.000000       9.000000       3.000000       1.000000  
50%         0.000000      10.000000       3.000000       1.000000  
75%         3.000000      12.000000       4.000000       2.000000  
max         3.000000      14.000000       6.000000       2.000000  

[8 rows x 21 columns]

In [7]:
df['age_1'].value_counts()
df['neuro_1'].value_counts()
df['cardi_1'].value_counts()
df['respi_1'].value_counts()
df['coagu_1'].value_counts()
df['renal_1'].value_counts()
df['icc_1'].value_counts()
df['ecog_1'].value_counts()
df['amib_total_1'].value_counts()

3    329999
2    230000
5    220000
4    210000
6     10000
Name: amib_total_1, dtype: int64

In [8]:
# Shape of Data
df.shape

(999999, 22)

In [9]:
df['age_2'].value_counts()
df['neuro_2'].value_counts()
df['cardi_2'].value_counts()
df['respi_2'].value_counts()
df['coagu_2'].value_counts()
df['renal_2'].value_counts()
df['icc_2'].value_counts()
df['ecog_2'].value_counts()
df['amib_total_2'].value_counts()

3    329999
2    230000
5    220000
4    210000
6     10000
Name: amib_total_2, dtype: int64

In [10]:
# Shape of Data
df.shape

(999999, 22)

In [11]:
# drop some colums we donot need like dates and id
df.drop(columns={'patients'},axis=1,inplace=True)
#df.shape

In [12]:
# CHECK  NULL Values
df.isnull().sum()

age_1           0
neuro_1         0
cardi_1         0
respi_1         0
coagu_1         0
hepat_1         0
renal_1         0
icc_1           0
ecog_1          0
amib_total_1    0
age_2           0
neuro_2         0
cardi_2         0
respi_2         0
coagu_2         0
hepat_2         0
renal_2         0
icc_2           0
ecog_2          0
amib_total_2    0
decisao         0
dtype: int64

In [13]:
df['decisao'].value_counts()

2    446400
1    446400
0    107199
Name: decisao, dtype: int64

In [14]:
X = df[['age_1', 'neuro_1', 'cardi_1', 'respi_1', 'coagu_1', 'hepat_1', 'renal_1', 'icc_1', 'ecog_1', 'amib_total_1','age_2', 'neuro_2', 'cardi_2', 'respi_2', 'coagu_2', 'hepat_2', 'renal_2', 'icc_2', 'ecog_2', 'amib_total_2']]
print(X)

        age_1  neuro_1  cardi_1  respi_1  coagu_1  hepat_1  renal_1  icc_1  \
0          82        1        4        4        1        3        1      0   
1          82        1        4        4        1        3        1      0   
2          82        1        4        4        1        3        1      0   
3          82        1        4        4        1        3        1      0   
4          82        1        4        4        1        3        1      0   
...       ...      ...      ...      ...      ...      ...      ...    ...   
999994     82        2        1        2        4        0        3      3   
999995     82        2        1        2        4        0        3      3   
999996     82        2        1        2        4        0        3      3   
999997     82        2        1        2        4        0        3      3   
999998     82        2        1        2        4        0        3      3   

        ecog_1  amib_total_1  age_2  neuro_2  cardi_2  respi_2 

In [15]:
df.shape

(999999, 21)

In [16]:
df['decisao'].replace([1,2,3],[1,0,2],inplace=True)
df['decisao'].value_counts().to_frame() 

decisao
0   553599
1   446400

In [17]:

y = df['decisao']
print(y)
y.shape

0         0
1         1
2         0
3         1
4         0
         ..
999994    0
999995    0
999996    0
999997    0
999998    0
Name: decisao, Length: 999999, dtype: int64


(999999,)

In [18]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2)

In [33]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [34]:
# instance of model
treeModel = DecisionTreeClassifier(criterion='entropy')

In [35]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [36]:
treeModel.feature_importances_


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.22454593, 0.17426085, 0.14509266,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.19649904, 0.25960152])

In [37]:
from sklearn import tree
tree.plot_tree(treeModel)

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
predTree = treeModel.predict(x_test)

In [ ]:
print(predTree)

[1 1 1 ... 1 1 0]


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
score = accuracy_score(y_test, predTree)

In [ ]:
print(score)

## rrr

1.0


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [ ]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [ ]:
ranForestPred = ranModel.predict(x_test)

In [ ]:
ranForestPred

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [ ]:
ranModel.score(x_test, y_test)

1.0

In [ ]:
ranModel

RandomForestClassifier(n_estimators=200)

In [ ]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [ ]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [ ]:
model = pd.read_pickle('Model_MDS.pickle')

In [ ]:
result = model.predict([[82,1,4,4,1,3,1,0,13,3,22,2,3,3,4,0,0,0,12,3]])
result

d:\MDS\MedicalDecisionSupport\venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [ ]:
#import pickle as plk

In [ ]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [ ]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)