In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree

In [3]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [4]:
df.head()

Empty DataFrame
Columns: [PATIENT, AGE, NEUROLOGICAL, CARDIOVASCULAR, RESPIRATORY, COAGULATION, HEPATIC, RENAL, ICC, ECOG, SCORE_MINOR_TOTAL, SCORE_FRAGILITY, SCORE_SOFA, CLASSIFICATION]
Index: []

In [5]:
df.describe()


PATIENT  AGE NEUROLOGICAL CARDIOVASCULAR RESPIRATORY COAGULATION  \
count        0    0            0              0           0           0   
unique       0    0            0              0           0           0   
top        NaN  NaN          NaN            NaN         NaN         NaN   
freq       NaN  NaN          NaN            NaN         NaN         NaN   

       HEPATIC RENAL  ICC ECOG SCORE_MINOR_TOTAL SCORE_FRAGILITY SCORE_SOFA  \
count        0     0    0    0                 0               0          0   
unique       0     0    0    0                 0               0          0   
top        NaN   NaN  NaN  NaN               NaN             NaN        NaN   
freq       NaN   NaN  NaN  NaN               NaN             NaN        NaN   

       CLASSIFICATION  
count               0  
unique              0  
top               NaN  
freq              NaN

In [6]:
df['AGE'].value_counts()

Series([], Name: AGE, dtype: int64)

In [7]:
# Shape of Data
df.shape

(0, 14)

In [8]:
# drop some colums we donot need like dates and id
df.drop(columns={'PATIENT'},axis=1,inplace=True)
#df.shape

In [9]:
df.shape

(0, 13)

In [10]:
df['NEUROLOGICAL'].value_counts()

Series([], Name: NEUROLOGICAL, dtype: int64)

In [11]:
df['CARDIOVASCULAR'].value_counts()

Series([], Name: CARDIOVASCULAR, dtype: int64)

In [12]:
df['RESPIRATORY'].value_counts()

Series([], Name: RESPIRATORY, dtype: int64)

In [13]:
df['COAGULATION'].value_counts()

Series([], Name: COAGULATION, dtype: int64)

In [14]:
df['HEPATIC'].value_counts()

Series([], Name: HEPATIC, dtype: int64)

In [15]:
df['RENAL'].value_counts()

Series([], Name: RENAL, dtype: int64)

In [16]:
df['ICC'].value_counts()


Series([], Name: ICC, dtype: int64)

In [17]:
df['ECOG'].value_counts()

Series([], Name: ECOG, dtype: int64)

In [18]:
df['SCORE_SOFA'].value_counts()

Series([], Name: SCORE_SOFA, dtype: int64)

In [19]:
df['SCORE_FRAGILITY'].value_counts()

Series([], Name: SCORE_FRAGILITY, dtype: int64)

In [20]:
# CHECK  NULL Values
df.isnull().sum()

AGE                  0.0
NEUROLOGICAL         0.0
CARDIOVASCULAR       0.0
RESPIRATORY          0.0
COAGULATION          0.0
HEPATIC              0.0
RENAL                0.0
ICC                  0.0
ECOG                 0.0
SCORE_MINOR_TOTAL    0.0
SCORE_FRAGILITY      0.0
SCORE_SOFA           0.0
CLASSIFICATION       0.0
dtype: float64

In [21]:
df['CLASSIFICATION'].value_counts()

Series([], Name: CLASSIFICATION, dtype: int64)

In [22]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR', 'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_MINOR_TOTAL', 'SCORE_FRAGILITY', 'SCORE_SOFA']]
print(X)

Empty DataFrame
Columns: [AGE, NEUROLOGICAL, CARDIOVASCULAR, RESPIRATORY, COAGULATION, HEPATIC, RENAL, ICC, ECOG, SCORE_MINOR_TOTAL, SCORE_FRAGILITY, SCORE_SOFA]
Index: []


In [23]:
df.shape

(0, 13)

In [24]:
df['CLASSIFICATION'].replace([1,2,3],[1,0,2],inplace=True)
df['CLASSIFICATION'].value_counts().to_frame() 

Empty DataFrame
Columns: [CLASSIFICATION]
Index: []

In [25]:

y = df['CLASSIFICATION']
print(y)
y.shape

Series([], Name: CLASSIFICATION, dtype: object)


(0,)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2)

ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

In [ ]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [ ]:
# instance of model
treeModel = DecisionTreeClassifier()

In [ ]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
predTree = treeModel.predict(x_test)

In [ ]:
print(predTree)

[25 23 17 20 25 20 26 10 25 16 20 13 18 14 17 25 30 16 26 21 11 21 14 25
 22 28 20 15 18 13 20 30 27 22 17 19 26 26 22  8 25 20 15 16 24 16 28 19
 24 15 21 21 15 19 25 15 21 21 16 15 18 12 12 26 19 22 26 15 16 19 21 14
 16 13 21 26 25 28 22 22 27 13 24 21 24 13 24 18 26 10 25 29  8 17 20 29
 22 17 23 25 18 19 21 17 18 12 19 20 18 13 21 18 11 14 21 12 24 25 17 20
 16 25 24 18 17 13 17 22 13 28 16 12 14 17 15 21 18 24 18 18 24 15 19 18
 10 13  9 23 20 29 24 20 21 26 28 19 13 17 15 25 16 13 22 20 19 25 21 20
 20 31 16 17 14 13  8 13 13 19 23 15 25 14 23 11 16 27 10 27 10 30 13 28
 22 23 19 17 27 15 18 22]


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
score = accuracy_score(y_test, predTree)

In [ ]:
print(score)

## rrr

0.66


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [ ]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [ ]:
ranForestPred = ranModel.predict(x_test)

In [ ]:
ranForestPred

array([25, 24, 17, 20, 25, 20, 26, 10, 25, 16, 19, 13, 18, 15, 17, 25, 28,
       14, 26, 21, 11, 21, 14, 24, 22, 30, 20, 15, 18, 12, 20, 30, 26, 22,
       16, 19, 29, 28, 20,  9, 23, 20, 15, 16, 23, 16, 27, 17, 24, 15, 21,
       23, 15, 20, 25, 15, 21, 21, 16, 15, 18, 12, 12, 29, 19, 22, 26, 15,
       16, 19, 21, 14, 16, 13, 21, 27, 25, 27, 23, 22, 28, 13, 24, 22, 22,
       14, 24, 17, 26,  9, 26, 35,  9, 14, 20, 27, 22, 17, 22, 25, 19, 22,
       20, 17, 16, 12, 18, 20, 18, 13, 21, 18, 11, 14, 21, 12, 24, 26, 17,
       18, 16, 25, 24, 18, 17, 13, 17, 22, 13, 30, 16, 12, 14, 17, 15, 21,
       18, 24, 18, 18, 24, 17, 18, 18, 10, 12,  7, 23, 20, 30, 24, 20, 21,
       23, 27, 19, 13, 16, 15, 24, 17, 14, 21, 20, 17, 25, 21, 20, 20, 28,
       16, 16, 14, 13,  6, 13, 13, 19, 23, 16, 25, 14, 22, 11, 15, 29, 10,
       28, 10, 30, 13, 27, 22, 23, 19, 15, 26, 15, 18, 22], dtype=int64)

In [ ]:
ranModel.score(x_test, y_test)

1.0

In [ ]:
ranModel

RandomForestClassifier(n_estimators=200)

In [ ]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [ ]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [ ]:
model = pd.read_pickle('Model_MDS.pickle')

In [ ]:
result = model.predict([[88, 3, 2, 2, 1, 2, 2, 2, 2, 12, 2, 7], [60, 0, 3, 2, 4, 2, 0, 2, 2, 11, 2, 4], [81, 4, 4, 4, 2, 4, 1, 2, 2, 19, 2, 7], [80, 3, 2, 0, 3, 1, 4, 2, 3, 13, 3, 6]])
result

d:\MDS\MedicalDecisionSupport\venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([14, 16, 16, 16], dtype=int64)

In [ ]:
result

array([14, 16, 16, 16], dtype=int64)

In [ ]:
#import pickle as plk

In [ ]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [ ]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)