In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [4]:
df.head()

PATIENT  AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
0       Jacob Larsen   83             1               1            2   
1       Allison Hill   30             2               0            3   
2     Susan Sandoval   64             4               3            4   
3      Melissa Smith   26             4               4            1   
4  Seth Campbell Jr.   72             2               1            4   

   COAGULATION  HEPATIC  RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  \
0            4        1      4    2     2                  6                2   
1            2        4      1    4     2                  7                2   
2            3        4      0    2     2                  6                2   
3            0        0      2    2     2                  3                2   
4            3        4      0    4     4                  9                4   

   SCORE_SOFA  CLASSIFICATION  
0          13              21  
1          12              21  
2          18              26  
3          11              16  
4          14              27

In [5]:
df.describe()


AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  \
count  200.000000    200.000000      200.000000   200.000000   200.000000   
mean    53.500000      1.895000        1.910000     1.970000     2.185000   
std     25.692812      1.412071        1.443022     1.420984     1.389398   
min     10.000000      0.000000        0.000000     0.000000     0.000000   
25%     30.750000      1.000000        1.000000     1.000000     1.000000   
50%     58.000000      2.000000        2.000000     2.000000     2.000000   
75%     75.000000      3.000000        3.000000     3.000000     3.000000   
max     95.000000      4.000000        4.000000     4.000000     4.000000   

          HEPATIC       RENAL         ICC       ECOG  SCORE_MINOR_TOTAL  \
count  200.000000  200.000000  200.000000  200.00000         200.000000   
mean     2.010000    2.175000    3.000000    2.30500           6.170000   
std      1.442325    1.419312    1.002509    1.23271           2.107918   
min      0.000000    0.000000    2.000000    0.00000           2.000000   
25%      1.000000    1.000000    2.000000    2.00000           5.000000   
50%      2.000000    2.000000    3.000000    2.00000           6.000000   
75%      3.000000    3.000000    4.000000    3.00000           8.000000   
max      4.000000    4.000000    4.000000    4.00000          11.000000   

       SCORE_FRAGILITY  SCORE_SOFA  CLASSIFICATION  
count        200.00000  200.000000      200.000000  
mean           2.30500   12.145000       20.620000  
std            1.23271    3.444313        4.923087  
min            0.00000    3.000000        9.000000  
25%            2.00000   10.000000       17.000000  
50%            2.00000   12.000000       21.000000  
75%            3.00000   14.000000       24.000000  
max            4.00000   22.000000       34.000000

In [6]:
df['AGE'].value_counts()

37    5
32    5
64    5
62    5
16    5
     ..
70    1
52    1
94    1
38    1
35    1
Name: AGE, Length: 71, dtype: int64

In [7]:
# Shape of Data
df.shape

(200, 14)

In [8]:
# drop some colums we donot need like dates and id
df.drop(columns={'PATIENT'},axis=1,inplace=True)
#df.shape

In [9]:
df.shape

(200, 13)

In [10]:
df['NEUROLOGICAL'].value_counts()

1    52
0    40
4    38
2    35
3    35
Name: NEUROLOGICAL, dtype: int64

In [11]:
df['CARDIOVASCULAR'].value_counts()

1    46
0    44
4    39
3    38
2    33
Name: CARDIOVASCULAR, dtype: int64

In [12]:
df['RESPIRATORY'].value_counts()

1    45
3    41
0    40
4    39
2    35
Name: RESPIRATORY, dtype: int64

In [13]:
df['COAGULATION'].value_counts()

3    52
4    43
2    37
1    35
0    33
Name: COAGULATION, dtype: int64

In [14]:
df['HEPATIC'].value_counts()

3    44
1    42
4    41
0    41
2    32
Name: HEPATIC, dtype: int64

In [15]:
df['RENAL'].value_counts()

4    48
2    42
3    42
0    35
1    33
Name: RENAL, dtype: int64

In [16]:
df['ICC'].value_counts()


2    100
4    100
Name: ICC, dtype: int64

In [17]:
df['ECOG'].value_counts()

2    77
4    44
3    37
0    22
1    20
Name: ECOG, dtype: int64

In [18]:
df['SCORE_SOFA'].value_counts()

10    24
12    24
11    24
14    22
13    22
8     13
9     13
15    11
16     9
17     7
18     6
19     6
7      6
6      5
20     2
5      2
22     1
4      1
21     1
3      1
Name: SCORE_SOFA, dtype: int64

In [19]:
df['SCORE_FRAGILITY'].value_counts()

2    77
4    44
3    37
0    22
1    20
Name: SCORE_FRAGILITY, dtype: int64

In [20]:
# CHECK  NULL Values
df.isnull().sum()

AGE                  0
NEUROLOGICAL         0
CARDIOVASCULAR       0
RESPIRATORY          0
COAGULATION          0
HEPATIC              0
RENAL                0
ICC                  0
ECOG                 0
SCORE_MINOR_TOTAL    0
SCORE_FRAGILITY      0
SCORE_SOFA           0
CLASSIFICATION       0
dtype: int64

In [21]:
df['CLASSIFICATION'].value_counts()

21    16
16    16
22    15
18    15
19    15
24    15
23    12
20    12
15    11
26    10
25    10
17     9
14     8
27     6
29     6
28     5
12     4
30     4
13     3
10     3
33     1
34     1
9      1
11     1
31     1
Name: CLASSIFICATION, dtype: int64

In [22]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR', 'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_MINOR_TOTAL', 'SCORE_FRAGILITY', 'SCORE_SOFA']]
print(X)

     AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  HEPATIC  \
0     83             1               1            2            4        1   
1     30             2               0            3            2        4   
2     64             4               3            4            3        4   
3     26             4               4            1            0        0   
4     72             2               1            4            3        4   
..   ...           ...             ...          ...          ...      ...   
195   15             2               1            4            0        4   
196   59             2               2            4            2        0   
197   76             1               3            2            0        0   
198   65             2               1            2            2        0   
199   80             0               3            4            1        1   

     RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  SCORE_SOFA  
0  

In [23]:
df.shape

(200, 13)

In [24]:
df['CLASSIFICATION'].replace([1,2,3],[1,0,2],inplace=True)
df['CLASSIFICATION'].value_counts().to_frame() 

CLASSIFICATION
21              16
16              16
22              15
18              15
19              15
24              15
23              12
20              12
15              11
26              10
25              10
17               9
14               8
27               6
29               6
28               5
12               4
30               4
13               3
10               3
33               1
34               1
9                1
11               1
31               1

In [25]:

y = df['CLASSIFICATION']
print(y)
y.shape

0      21
1      21
2      26
3      16
4      27
       ..
195    21
196    23
197    16
198    10
199    21
Name: CLASSIFICATION, Length: 200, dtype: int64


(200,)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [27]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [28]:
# instance of model
treeModel = DecisionTreeClassifier()

In [29]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [30]:
predTree = treeModel.predict(x_test)

In [31]:
print(predTree)

[24 22 23 17 22 11 17 25 22 22 10 26 19 20 22 23 19 22 18 23 19 26 20 25
 14 19 12 16 20 21 22 20 21 21 23 27 29 21 17 17]


In [32]:
from sklearn.metrics import accuracy_score

In [33]:
score = accuracy_score(y_test, predTree)

In [34]:
print(score)

0.2


In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [37]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [38]:
ranForestPred = ranModel.predict(x_test)

In [39]:
ranForestPred

array([25, 23, 25, 14, 20, 10, 19, 27, 25, 19, 13, 29, 19, 17, 23, 24, 15,
       24, 17, 23, 19, 24, 18, 24, 15, 18, 12, 18, 18, 21, 22, 18, 24, 21,
       21, 30, 28, 28, 17, 16], dtype=int64)

In [40]:
ranModel.score(x_test, y_test)

1.0

In [41]:
ranModel

RandomForestClassifier(n_estimators=200)

In [42]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [43]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [44]:
model = pd.read_pickle('Model_MDS.pickle')

In [45]:
result = model.predict([[54, 4, 4, 2, 4, 1, 1, 4, 4, 29, 4,12]])
result

d:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([24], dtype=int64)

In [46]:
result

array([24], dtype=int64)

In [47]:
#import pickle as plk

In [48]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [49]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)