In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [4]:
df.head()

PATIENT  AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
0   Michael Roberts   74             0               1            0   
1  Elizabeth Wilson   24             1               0            0   
2  Ronald Robertson   48             2               0            0   
3  Andrew Nicholson   44             1               0            0   
4       Craig Drake   56             0               1            0   

   COAGULATION  HEPATIC  RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  \
0            0        0      0    2     0                  4                0   
1            0        1      2    2     0                  2                0   
2            0        0      1    2     2                  2                2   
3            0        0      3    2     1                  2                1   
4            0        0      1    2     2                  3                2   

   SCORE_SOFA  CLASSIFICATION  
0           1               1  
1           4               2  
2           3               3  
3           4               4  
4           2               5

In [5]:
df.describe()


AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  \
count  1000.000000    1000.00000     1000.000000   1000.00000  1000.000000   
mean     52.663000       1.99500        1.995000      2.02100     2.017000   
std      24.887202       1.43214        1.398188      1.42569     1.430649   
min      10.000000       0.00000        0.000000      0.00000     0.000000   
25%      32.000000       1.00000        1.000000      1.00000     1.000000   
50%      52.500000       2.00000        2.000000      2.00000     2.000000   
75%      74.000000       3.00000        3.000000      3.00000     3.000000   
max      95.000000       4.00000        4.000000      4.00000     4.000000   

           HEPATIC        RENAL          ICC         ECOG  SCORE_MINOR_TOTAL  \
count  1000.000000  1000.000000  1000.000000  1000.000000         1000.00000   
mean      2.011000     1.941000     2.972000     1.463000            6.05000   
std       1.402443     1.390486     1.000108     1.112596            2.12415   
min       0.000000     0.000000     2.000000     0.000000            2.00000   
25%       1.000000     1.000000     2.000000     0.000000            4.00000   
50%       2.000000     2.000000     2.000000     1.000000            6.00000   
75%       3.000000     3.000000     4.000000     2.000000            8.00000   
max       4.000000     4.000000     4.000000     3.000000           11.00000   

       SCORE_FRAGILITY   SCORE_SOFA  CLASSIFICATION  
count      1000.000000  1000.000000     1000.000000  
mean          1.463000    11.980000        5.500000  
std           1.112596     3.404878        2.873719  
min           0.000000     1.000000        1.000000  
25%           0.000000    10.000000        3.000000  
50%           1.000000    12.000000        5.500000  
75%           2.000000    14.000000        8.000000  
max           3.000000    22.000000       10.000000

In [6]:
df['AGE'].value_counts()

20    22
47    19
29    19
35    19
92    19
      ..
36     5
60     5
27     5
22     5
50     4
Name: AGE, Length: 86, dtype: int64

In [7]:
# Shape of Data
df.shape

(1000, 14)

In [8]:
# drop some colums we donot need like dates and id
df.drop(columns={'PATIENT'},axis=1,inplace=True)
#df.shape

In [9]:
df.shape

(1000, 13)

In [10]:
df['NEUROLOGICAL'].value_counts()

4    211
0    208
2    208
1    192
3    181
Name: NEUROLOGICAL, dtype: int64

In [11]:
df['CARDIOVASCULAR'].value_counts()

1    218
2    202
4    197
3    195
0    188
Name: CARDIOVASCULAR, dtype: int64

In [12]:
df['RESPIRATORY'].value_counts()

4    207
3    203
0    202
2    196
1    192
Name: RESPIRATORY, dtype: int64

In [13]:
df['COAGULATION'].value_counts()

3    209
4    207
1    204
0    201
2    179
Name: COAGULATION, dtype: int64

In [14]:
df['HEPATIC'].value_counts()

1    214
3    211
4    196
2    190
0    189
Name: HEPATIC, dtype: int64

In [15]:
df['RENAL'].value_counts()

2    220
1    216
0    198
4    187
3    179
Name: RENAL, dtype: int64

In [16]:
df['ICC'].value_counts()


2    514
4    486
Name: ICC, dtype: int64

In [17]:
df['ECOG'].value_counts()

0    258
1    257
2    249
3    236
Name: ECOG, dtype: int64

In [18]:
df['SCORE_SOFA'].value_counts()

11    123
13    123
10    107
12     94
14     88
15     81
9      80
8      60
16     54
7      37
17     37
18     34
6      27
19     19
5      13
4       9
20      7
3       3
21      1
1       1
2       1
22      1
Name: SCORE_SOFA, dtype: int64

In [19]:
df['SCORE_FRAGILITY'].value_counts()

0    258
1    257
2    249
3    236
Name: SCORE_FRAGILITY, dtype: int64

In [20]:
# CHECK  NULL Values
df.isnull().sum()

AGE                  0
NEUROLOGICAL         0
CARDIOVASCULAR       0
RESPIRATORY          0
COAGULATION          0
HEPATIC              0
RENAL                0
ICC                  0
ECOG                 0
SCORE_MINOR_TOTAL    0
SCORE_FRAGILITY      0
SCORE_SOFA           0
CLASSIFICATION       0
dtype: int64

In [21]:
df['CLASSIFICATION'].value_counts()

1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
Name: CLASSIFICATION, dtype: int64

In [22]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR', 'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_MINOR_TOTAL', 'SCORE_FRAGILITY', 'SCORE_SOFA']]
print(X)

     AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  HEPATIC  \
0     74             0               1            0            0        0   
1     24             1               0            0            0        1   
2     48             2               0            0            0        0   
3     44             1               0            0            0        0   
4     56             0               1            0            0        0   
..   ...           ...             ...          ...          ...      ...   
995   84             4               3            1            4        3   
996   90             2               3            2            3        4   
997   74             4               2            4            2        3   
998   92             1               4            4            4        3   
999   76             4               3            2            4        3   

     RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  SCORE_SOFA  
0  

In [23]:
df.shape

(1000, 13)

In [24]:
df['CLASSIFICATION'].replace([1,2,3],[1,0,2],inplace=True)
df['CLASSIFICATION'].value_counts().to_frame() 

CLASSIFICATION
1              100
0              100
2              100
4              100
5              100
6              100
7              100
8              100
9              100
10             100

In [25]:

y = df['CLASSIFICATION']
print(y)
y.shape

0       1
1       0
2       2
3       4
4       5
       ..
995     6
996     7
997     8
998     9
999    10
Name: CLASSIFICATION, Length: 1000, dtype: int64


(1000,)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [27]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [28]:
# instance of model
treeModel = DecisionTreeClassifier()

In [29]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [30]:
predTree = treeModel.predict(x_test)

In [31]:
print(predTree)

[ 2  1  1  0  9  2  7  1  5  2  5  5  2  5  9  5  8  8  2  1  6  0 10  6
  0  2 10  6  0  6  9  0 10  0  6  6  6  0  1  5  5  1  5  1  0  8  1  2
  6  1 10  7  2  5  8  4  5  5  7  8  5  8 10  1  8  7 10  1  2  7 10  4
  1  9  9  0  8  1  6  2  8  6  9  6  2  4  1  1 10 10  6  1  8  6  2 10
  4 10  7  7  9  8  0  7  6  6  4  2  2  2  1  1  2  8  7 10  7  2  2  5
  9 10  1  7  8  9  5  8 10 10 10  5  6  9 10  7  9  7  0  7  7  8  6  8
  0  6  7  6  1  2  7  4 10  8  1 10  7 10  8  2  2  5  4  9  7  7  1  8
  4  9  9  8  2  1 10  4  4  0  7  6  8  0 10  8  5  5  7  2  8  1  6  5
  8  8  4  1  5  6 10  2]


In [32]:
from sklearn.metrics import accuracy_score

In [33]:
score = accuracy_score(y_test, predTree)

In [34]:
print(score)

0.1


In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [37]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [38]:
ranForestPred = ranModel.predict(x_test)

In [39]:
ranForestPred

array([ 8,  9,  2,  9,  2, 10,  2,  1,  9, 10,  7,  2,  9,  6,  0,  4,  5,
        7,  1,  7,  2,  2,  9,  2,  4, 10,  9,  8, 10,  5,  1,  9,  5,  5,
        5,  5,  9,  0,  5,  5,  2,  0,  1,  0,  5,  8,  8,  0,  4,  6,  4,
        5, 10,  6,  9,  6,  6,  8,  7,  6,  8,  9,  6,  5,  2,  2,  5,  7,
        9,  8, 10,  1,  0,  5,  8,  6,  0,  9,  0,  9,  6,  2,  7,  8,  0,
        2,  4,  4,  4,  8,  5, 10,  8,  7,  5,  0, 10,  4,  9,  5,  6,  4,
        0,  7,  9,  5,  8,  9,  7,  5, 10,  6,  1, 10,  9,  6,  0, 10,  1,
        5,  1,  0,  4,  5,  8,  4, 10,  7,  6,  2,  0,  9, 10,  2,  8,  1,
        7,  8,  9, 10,  4,  8,  9,  6,  0, 10,  2,  7,  6,  2,  5,  1,  9,
        0,  7,  7,  6,  0,  5,  9, 10,  6,  6,  9,  8,  4,  5,  8,  8,  6,
        2,  0,  5,  4,  9,  0,  7,  7,  0,  8,  7,  1,  4,  2,  0,  5,  1,
        4,  8,  4, 10,  7,  4,  5,  5,  1,  5,  1,  9,  8], dtype=int64)

In [40]:
ranModel.score(x_test, y_test)

1.0

In [41]:
ranModel

RandomForestClassifier(n_estimators=200)

In [42]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [43]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [44]:
model = pd.read_pickle('Model_MDS.pickle')

In [45]:
#result = model.predict([[88, 3, 2, 2, 1, 2, 2, 2, 2, 12, 2, 7], [60, 0, 3, 2, 4, 2, 0, 2, 2, 11, 2, 4], [81, 4, 4, 4, 2, 4, 1, 2, 2, 19, 2, 7], [80, 3, 2, 0, 3, 1, 4, 2, 3, 13, 3, 6]])
result = model.predict([[88, 3, 2, 2, 1, 2, 2, 2, 2, 12, 2, 7]])
result

d:\MDS\MedicalDecisionSupport\venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [46]:
result

array([0], dtype=int64)

In [47]:
#import pickle as plk

In [48]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [49]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)