In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree

In [3]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [4]:
df.head()

PATIENT  AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
0  Cynthia Estrada   79             4               0            0   
1       John Jones   15             1               1            0   
2    Debbie Parker   20             1               3            1   
3    Lindsay Gomez   51             3               1            3   
4        John Boyd   47             2               1            0   

   COAGULATION  HEPATIC  RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  \
0            4        4      1    2     1                  6                1   
1            3        3      3    2     3                  3                3   
2            4        3      3    4     1                  8                1   
3            4        3      4    4     2                  9                2   
4            1        3      1    4     3                  5                3   

   SCORE_SOFA  CLASSIFICATION  
0          13              20  
1          11              17  
2          15              24  
3          18              29  
4           8              16

In [5]:
df.describe()


AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  \
count  100.000000    100.000000      100.000000     100.0000   100.000000   
mean    51.130000      1.950000        1.930000       2.0400     1.790000   
std     25.652162      1.388081        1.335264       1.3478     1.578229   
min     11.000000      0.000000        0.000000       0.0000     0.000000   
25%     28.750000      1.000000        1.000000       1.0000     0.000000   
50%     51.000000      2.000000        2.000000       2.0000     1.000000   
75%     72.000000      3.000000        3.000000       3.0000     3.000000   
max     95.000000      4.000000        4.000000       4.0000     4.000000   

          HEPATIC       RENAL         ICC       ECOG  SCORE_MINOR_TOTAL  \
count  100.000000  100.000000  100.000000  100.00000         100.000000   
mean     1.960000    1.850000    3.040000    1.44000           6.010000   
std      1.399278    1.416889    1.004233    1.16619           2.240558   
min      0.000000    0.000000    2.000000    0.00000           2.000000   
25%      1.000000    0.000000    2.000000    0.00000           4.750000   
50%      2.000000    2.000000    4.000000    1.00000           6.000000   
75%      3.000000    3.000000    4.000000    3.00000           8.000000   
max      4.000000    4.000000    4.000000    3.00000          11.000000   

       SCORE_FRAGILITY  SCORE_SOFA  CLASSIFICATION  
count        100.00000  100.000000       100.00000  
mean           1.44000   11.520000        18.97000  
std            1.16619    3.785886         5.38508  
min            0.00000    2.000000         7.00000  
25%            0.00000    9.000000        14.75000  
50%            1.00000   11.000000        19.50000  
75%            3.00000   14.000000        22.25000  
max            3.00000   19.000000        30.00000

In [6]:
df['AGE'].value_counts()

29    3
45    3
21    3
13    3
54    3
     ..
70    1
19    1
28    1
81    1
83    1
Name: AGE, Length: 61, dtype: int64

In [7]:
# Shape of Data
df.shape

(100, 14)

In [8]:
# drop some colums we donot need like dates and id
df.drop(columns={'PATIENT'},axis=1,inplace=True)
#df.shape

In [9]:
df.shape

(100, 13)

In [10]:
df['NEUROLOGICAL'].value_counts()

2    26
0    20
4    19
1    19
3    16
Name: NEUROLOGICAL, dtype: int64

In [11]:
df['CARDIOVASCULAR'].value_counts()

2    28
1    21
0    18
4    17
3    16
Name: CARDIOVASCULAR, dtype: int64

In [12]:
df['RESPIRATORY'].value_counts()

2    25
1    21
3    19
4    19
0    16
Name: RESPIRATORY, dtype: int64

In [13]:
df['COAGULATION'].value_counts()

0    31
4    23
1    20
3    15
2    11
Name: COAGULATION, dtype: int64

In [14]:
df['HEPATIC'].value_counts()

3    27
0    23
2    20
4    15
1    15
Name: HEPATIC, dtype: int64

In [15]:
df['RENAL'].value_counts()

0    26
2    25
3    19
4    16
1    14
Name: RENAL, dtype: int64

In [16]:
df['ICC'].value_counts()


4    52
2    48
Name: ICC, dtype: int64

In [17]:
df['ECOG'].value_counts()

0    29
3    26
1    24
2    21
Name: ECOG, dtype: int64

In [18]:
df['SCORE_SOFA'].value_counts()

9     11
12    10
11    10
14     8
8      8
10     8
13     7
15     7
17     6
7      6
16     5
18     4
4      3
6      3
19     2
2      1
5      1
Name: SCORE_SOFA, dtype: int64

In [19]:
df['SCORE_FRAGILITY'].value_counts()

0    29
3    26
1    24
2    21
Name: SCORE_FRAGILITY, dtype: int64

In [20]:
# CHECK  NULL Values
df.isnull().sum()

AGE                  0
NEUROLOGICAL         0
CARDIOVASCULAR       0
RESPIRATORY          0
COAGULATION          0
HEPATIC              0
RENAL                0
ICC                  0
ECOG                 0
SCORE_MINOR_TOTAL    0
SCORE_FRAGILITY      0
SCORE_SOFA           0
CLASSIFICATION       0
dtype: int64

In [21]:
df['CLASSIFICATION'].value_counts()

21    12
14     9
20     8
18     8
24     7
16     6
12     5
22     5
17     5
26     5
19     4
23     4
13     4
30     3
28     3
8      3
15     2
7      1
9      1
10     1
27     1
29     1
25     1
11     1
Name: CLASSIFICATION, dtype: int64

In [22]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR', 'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_MINOR_TOTAL', 'SCORE_FRAGILITY', 'SCORE_SOFA']]
print(X)

    AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  HEPATIC  \
0    79             4               0            0            4        4   
1    15             1               1            0            3        3   
2    20             1               3            1            4        3   
3    51             3               1            3            4        3   
4    47             2               1            0            1        3   
..  ...           ...             ...          ...          ...      ...   
95   58             3               2            3            4        1   
96   25             2               4            0            3        1   
97   92             4               2            2            4        2   
98   89             3               1            2            2        2   
99   12             3               3            4            0        2   

    RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  SCORE_SOFA  
0       1    2  

In [23]:
df.shape

(100, 13)

In [24]:
df['CLASSIFICATION'].replace([1,2,3],[1,0,2],inplace=True)
df['CLASSIFICATION'].value_counts().to_frame() 

CLASSIFICATION
21              12
14               9
20               8
18               8
24               7
16               6
12               5
22               5
17               5
26               5
19               4
23               4
13               4
30               3
28               3
8                3
15               2
7                1
9                1
10               1
27               1
29               1
25               1
11               1

In [25]:

y = df['CLASSIFICATION']
print(y)
y.shape

0     20
1     17
2     24
3     29
4     16
      ..
95    23
96    21
97    30
98    20
99    19
Name: CLASSIFICATION, Length: 100, dtype: int64


(100,)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [27]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [28]:
# instance of model
treeModel = DecisionTreeClassifier()

In [31]:
# treeModel.

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
predTree = treeModel.predict(x_test)

In [ ]:
print(predTree)

[1]


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
score = accuracy_score(y_test, predTree)

In [ ]:
print(score)

0.0


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [ ]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [ ]:
ranForestPred = ranModel.predict(x_test)

In [ ]:
ranForestPred

array([4], dtype=int64)

In [ ]:
ranModel.score(x_test, y_test)

1.0

In [ ]:
ranModel

RandomForestClassifier(n_estimators=200)

In [ ]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [ ]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [ ]:
model = pd.read_pickle('Model_MDS.pickle')

In [ ]:
result = model.predict([[54, 4, 4, 2, 4, 1, 1, 4, 4, 29, 4,12]])
result

d:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

In [ ]:
result

array([4], dtype=int64)

In [ ]:
#import pickle as plk

In [ ]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [ ]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)