In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree

In [3]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [4]:
df.head()

PATIENT  AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
0     Kristen Jenkins   32             1               2            2   
1       Amanda Nelson   92             0               1            1   
2         Darren Hall   30             1               4            0   
3  Christina Castillo   58             4               4            1   
4       Jacob Daniels   80             1               3            3   

   COAGULATION  HEPATIC  RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  \
0            0        3      4    2     0                  4                0   
1            1        3      4    2     2                  6                2   
2            3        3      1    4     0                  7                0   
3            4        0      3    4     0                  9                0   
4            2        4      3    4     0                 10                0   

   SCORE_SOFA  CLASSIFICATION  
0          12               0  
1          10               0  
2          12               0  
3          16               0  
4          16               0

In [5]:
df.describe()


AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  \
count  1888.000000   1888.000000     1888.000000  1888.000000  1888.000000   
mean     51.537076      1.958157        2.012182     2.014831     2.048199   
std      24.690768      1.415654        1.413599     1.423474     1.405307   
min      10.000000      0.000000        0.000000     0.000000     0.000000   
25%      30.750000      1.000000        1.000000     1.000000     1.000000   
50%      51.000000      2.000000        2.000000     2.000000     2.000000   
75%      72.000000      3.000000        3.000000     3.000000     3.000000   
max      95.000000      4.000000        4.000000     4.000000     4.000000   

           HEPATIC        RENAL          ICC         ECOG  SCORE_MINOR_TOTAL  \
count  1888.000000  1888.000000  1888.000000  1888.000000        1888.000000   
mean      1.986229     2.038665     3.002119     0.585805           6.083686   
std       1.412647     1.399935     1.000263     1.020744           2.085707   
min       0.000000     0.000000     2.000000     0.000000           2.000000   
25%       1.000000     1.000000     2.000000     0.000000           5.000000   
50%       2.000000     2.000000     4.000000     0.000000           6.000000   
75%       3.000000     3.000000     4.000000     1.000000           8.000000   
max       4.000000     4.000000     4.000000     3.000000          11.000000   

       SCORE_FRAGILITY   SCORE_SOFA  CLASSIFICATION  
count      1888.000000  1888.000000          1888.0  
mean          0.585805    12.058263             0.0  
std           1.020744     3.520219             0.0  
min           0.000000     2.000000             0.0  
25%           0.000000    10.000000             0.0  
50%           0.000000    12.000000             0.0  
75%           1.000000    15.000000             0.0  
max           3.000000    22.000000             0.0

In [6]:
df['AGE'].value_counts()

65    34
42    32
50    32
10    31
86    31
      ..
20    15
73    15
87    15
78    12
75    11
Name: AGE, Length: 86, dtype: int64

In [7]:
# Shape of Data
df.shape

(1888, 14)

In [8]:
# drop some colums we donot need like dates and id
df.drop(columns={'PATIENT'},axis=1,inplace=True)
#df.shape

In [9]:
df.shape

(1888, 13)

In [10]:
df['NEUROLOGICAL'].value_counts()

0    400
3    379
2    377
1    374
4    358
Name: NEUROLOGICAL, dtype: int64

In [11]:
df['CARDIOVASCULAR'].value_counts()

1    393
4    383
3    382
0    366
2    364
Name: CARDIOVASCULAR, dtype: int64

In [12]:
df['RESPIRATORY'].value_counts()

3    401
0    385
4    380
1    363
2    359
Name: RESPIRATORY, dtype: int64

In [13]:
df['COAGULATION'].value_counts()

3    397
2    389
4    385
0    359
1    358
Name: COAGULATION, dtype: int64

In [14]:
df['HEPATIC'].value_counts()

2    402
0    397
3    384
4    363
1    342
Name: HEPATIC, dtype: int64

In [15]:
df['RENAL'].value_counts()

2    416
3    386
4    379
0    364
1    343
Name: RENAL, dtype: int64

In [16]:
df['ICC'].value_counts()


4    946
2    942
Name: ICC, dtype: int64

In [17]:
df['ECOG'].value_counts()

0    1340
3     196
1     186
2     166
Name: ECOG, dtype: int64

In [18]:
df['SCORE_SOFA'].value_counts()

13    209
11    202
12    197
10    178
14    178
9     157
15    156
16    114
8     113
17     86
7      67
18     60
6      49
5      37
19     29
20     16
4      15
21     10
3       9
2       4
22      2
Name: SCORE_SOFA, dtype: int64

In [19]:
df['SCORE_FRAGILITY'].value_counts()

0    1340
3     196
1     186
2     166
Name: SCORE_FRAGILITY, dtype: int64

In [20]:
# CHECK  NULL Values
df.isnull().sum()

AGE                  0
NEUROLOGICAL         0
CARDIOVASCULAR       0
RESPIRATORY          0
COAGULATION          0
HEPATIC              0
RENAL                0
ICC                  0
ECOG                 0
SCORE_MINOR_TOTAL    0
SCORE_FRAGILITY      0
SCORE_SOFA           0
CLASSIFICATION       0
dtype: int64

In [21]:
df['CLASSIFICATION'].value_counts()

0    1888
Name: CLASSIFICATION, dtype: int64

In [22]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR', 'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_MINOR_TOTAL', 'SCORE_FRAGILITY', 'SCORE_SOFA']]
print(X)

      AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  HEPATIC  \
0      32             1               2            2            0        3   
1      92             0               1            1            1        3   
2      30             1               4            0            3        3   
3      58             4               4            1            4        0   
4      80             1               3            3            2        4   
...   ...           ...             ...          ...          ...      ...   
1883   47             1               2            1            3        1   
1884   37             1               3            3            3        4   
1885   82             2               3            0            3        2   
1886   82             0               3            4            4        0   
1887   40             3               3            4            3        1   

      RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  SCO

In [23]:
df.shape

(1888, 13)

In [24]:
df['CLASSIFICATION'].replace([1,2,3],[1,0,2],inplace=True)
df['CLASSIFICATION'].value_counts().to_frame() 

CLASSIFICATION
0            1888

In [25]:

y = df['CLASSIFICATION']
print(y)
y.shape

0       0
1       0
2       0
3       0
4       0
       ..
1883    0
1884    0
1885    0
1886    0
1887    0
Name: CLASSIFICATION, Length: 1888, dtype: int64


(1888,)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2)

In [27]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [28]:
# instance of model
treeModel = DecisionTreeClassifier()

In [29]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [30]:
predTree = treeModel.predict(x_test)

In [31]:
print(predTree)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0]


In [32]:
from sklearn.metrics import accuracy_score

In [33]:
score = accuracy_score(y_test, predTree)

In [34]:
print(score)

## rrr

1.0


In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [37]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [38]:
ranForestPred = ranModel.predict(x_test)

In [39]:
ranForestPred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [40]:
ranModel.score(x_test, y_test)

1.0

In [41]:
ranModel

RandomForestClassifier(n_estimators=200)

In [42]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [43]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [44]:
model = pd.read_pickle('Model_MDS.pickle')

In [45]:
result = model.predict([[88, 3, 2, 2, 1, 2, 2, 2, 2, 12, 2, 7], [60, 0, 3, 2, 4, 2, 0, 2, 2, 11, 2, 4], [81, 4, 4, 4, 2, 4, 1, 2, 2, 19, 2, 7], [80, 3, 2, 0, 3, 1, 4, 2, 3, 13, 3, 6]])
result

d:\MDS\MedicalDecisionSupport\venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0], dtype=int64)

In [46]:
result

array([0, 0, 0, 0], dtype=int64)

In [47]:
#import pickle as plk

In [48]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [49]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)