In [19]:
import pandas as pd
import numpy as np

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [22]:
df.head()

PATIENT  AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
0       Jacob Larsen   83             1               1            2   
1       Allison Hill   30             2               0            3   
2     Susan Sandoval   64             4               3            4   
3      Melissa Smith   26             4               4            1   
4  Seth Campbell Jr.   72             2               1            4   

   COAGULATION  HEPATIC  RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  \
0            4        1      4    2     2                  6                2   
1            2        4      1    4     2                  7                2   
2            3        4      0    2     2                  6                2   
3            0        0      2    2     2                  3                2   
4            3        4      0    4     4                  9                4   

   SCORE_SOFA  CLASSIFICATION  
0          13              21  
1          12              21  
2          18              26  
3          11              16  
4          14              27

In [23]:
df.describe()


AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  \
count  100.000000    100.000000      100.000000   100.000000   100.000000   
mean    55.450000      1.810000        1.990000     2.160000     2.280000   
std     25.744029      1.454321        1.431923     1.390589     1.333939   
min     10.000000      0.000000        0.000000     0.000000     0.000000   
25%     32.000000      1.000000        1.000000     1.000000     1.000000   
50%     59.500000      2.000000        2.000000     2.000000     2.500000   
75%     77.250000      3.000000        3.000000     3.000000     3.000000   
max     95.000000      4.000000        4.000000     4.000000     4.000000   

          HEPATIC       RENAL         ICC        ECOG  SCORE_MINOR_TOTAL  \
count  100.000000  100.000000  100.000000  100.000000         100.000000   
mean     2.160000    2.240000    2.980000    2.880000           6.330000   
std      1.383306    1.450322    1.004837    0.997775           2.040276   
min      0.000000    0.000000    2.000000    2.000000           2.000000   
25%      1.000000    1.000000    2.000000    2.000000           5.000000   
50%      2.000000    2.000000    2.000000    2.000000           6.000000   
75%      3.000000    4.000000    4.000000    4.000000           8.000000   
max      4.000000    4.000000    4.000000    4.000000          11.000000   

       SCORE_FRAGILITY  SCORE_SOFA  CLASSIFICATION  
count       100.000000  100.000000       100.00000  
mean          2.880000   12.640000        21.85000  
std           0.997775    3.301423         4.84794  
min           2.000000    7.000000        12.00000  
25%           2.000000   10.000000        18.75000  
50%           2.000000   12.000000        22.00000  
75%           4.000000   14.000000        25.25000  
max           4.000000   22.000000        34.00000

In [24]:
df['AGE'].value_counts()

60    5
19    3
42    3
64    3
32    3
72    3
84    3
91    3
16    3
90    3
78    2
13    2
58    2
44    2
24    2
71    2
53    2
17    2
62    2
37    2
83    2
73    2
50    2
26    2
51    2
59    2
25    2
45    2
67    2
95    2
92    2
61    1
77    1
94    1
76    1
14    1
68    1
11    1
63    1
10    1
75    1
38    1
52    1
18    1
89    1
20    1
30    1
79    1
93    1
88    1
80    1
43    1
22    1
86    1
40    1
87    1
55    1
Name: AGE, dtype: int64

In [25]:
# Shape of Data
df.shape

(100, 14)

In [26]:
# drop some colums we donot need like dates and id
df.drop(columns={'PATIENT'},axis=1,inplace=True)
#df.shape

In [27]:
df.shape

(100, 13)

In [28]:
df['NEUROLOGICAL'].value_counts()

1    24
0    24
4    20
2    19
3    13
Name: NEUROLOGICAL, dtype: int64

In [29]:
df['CARDIOVASCULAR'].value_counts()

1    25
3    22
4    20
0    19
2    14
Name: CARDIOVASCULAR, dtype: int64

In [30]:
df['RESPIRATORY'].value_counts()

3    23
4    22
2    20
1    19
0    16
Name: RESPIRATORY, dtype: int64

In [31]:
df['COAGULATION'].value_counts()

3    29
4    21
2    21
1    15
0    14
Name: COAGULATION, dtype: int64

In [32]:
df['HEPATIC'].value_counts()

3    23
4    22
1    21
2    19
0    15
Name: HEPATIC, dtype: int64

In [33]:
df['RENAL'].value_counts()

4    28
2    21
3    18
0    17
1    16
Name: RENAL, dtype: int64

In [34]:
df['ICC'].value_counts()


2    51
4    49
Name: ICC, dtype: int64

In [35]:
df['ECOG'].value_counts()

2    56
4    44
Name: ECOG, dtype: int64

In [36]:
df['SCORE_SOFA'].value_counts()

12    14
14    14
11    13
13     9
8      9
10     8
15     7
18     6
9      6
19     4
16     3
7      3
17     2
22     1
20     1
Name: SCORE_SOFA, dtype: int64

In [37]:
df['SCORE_FRAGILITY'].value_counts()

2    56
4    44
Name: SCORE_FRAGILITY, dtype: int64

In [38]:
# CHECK  NULL Values
df.isnull().sum()

AGE                  0
NEUROLOGICAL         0
CARDIOVASCULAR       0
RESPIRATORY          0
COAGULATION          0
HEPATIC              0
RENAL                0
ICC                  0
ECOG                 0
SCORE_MINOR_TOTAL    0
SCORE_FRAGILITY      0
SCORE_SOFA           0
CLASSIFICATION       0
dtype: int64

In [39]:
df['CLASSIFICATION'].value_counts()

19    9
26    9
20    8
24    8
22    7
25    7
21    6
18    6
16    5
27    5
23    5
15    5
29    4
30    4
12    3
14    3
17    3
33    1
28    1
34    1
Name: CLASSIFICATION, dtype: int64

In [42]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR', 'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_MINOR_TOTAL', 'SCORE_FRAGILITY', 'SCORE_SOFA']]
print(X)

    AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  HEPATIC  \
0    83             1               1            2            4        1   
1    30             2               0            3            2        4   
2    64             4               3            4            3        4   
3    26             4               4            1            0        0   
4    72             2               1            4            3        4   
..  ...           ...             ...          ...          ...      ...   
95   55             1               2            1            1        3   
96   84             1               2            3            0        3   
97   53             1               4            4            3        2   
98   84             0               3            1            3        3   
99   19             2               4            1            2        3   

    RENAL  ICC  ECOG  SCORE_MINOR_TOTAL  SCORE_FRAGILITY  SCORE_SOFA  
0       4    2  

In [43]:
df.shape

(100, 13)

In [44]:
df['CLASSIFICATION'].replace([1,2,3],[1,0,2],inplace=True)
df['CLASSIFICATION'].value_counts().to_frame() 

CLASSIFICATION
19               9
26               9
20               8
24               8
22               7
25               7
21               6
18               6
16               5
27               5
23               5
15               5
29               4
30               4
12               3
14               3
17               3
33               1
28               1
34               1

In [45]:

y = df['CLASSIFICATION']
print(y)
y.shape

0     21
1     21
2     26
3     16
4     27
      ..
95    19
96    20
97    30
98    20
99    23
Name: CLASSIFICATION, Length: 100, dtype: int64


(100,)

In [46]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [47]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [48]:
# instance of model
treeModel = DecisionTreeClassifier()

In [49]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [50]:
predTree = treeModel.predict(x_test)

In [51]:
print(predTree)

[15 29 24 22 12 17 25 29 17 15 23 17 18 26 19 30 16 16 17 22]


In [52]:
from sklearn.metrics import accuracy_score

In [53]:
score = accuracy_score(y_test, predTree)

In [54]:
print(score)

0.2


In [55]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [57]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [58]:
ranForestPred = ranModel.predict(x_test)

In [59]:
ranForestPred

array([14, 34, 19, 22, 12, 22, 27, 25, 17, 14, 21, 12, 19, 27, 19, 26, 15,
       18, 20, 26], dtype=int64)

In [60]:
ranModel.score(x_test, y_test)

1.0

In [61]:
ranModel

RandomForestClassifier(n_estimators=200)

In [62]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [63]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [64]:
model = pd.read_pickle('Model_MDS.pickle')

In [67]:
result = model.predict([[54, 4, 4, 2, 4, 1, 1, 4, 4, 29, 4,12]])
result

d:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([21], dtype=int64)

In [68]:
result

array([21], dtype=int64)

In [69]:
#import pickle as plk

In [70]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [71]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)