In [101]:
import pandas as pd
import numpy as np

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
# read Data
df = pd.read_csv('data_Calculate.csv')

In [104]:
df.head()

ID     PATIENT  AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
0   1     GERLIAN   14             2               2            1   
1   2   IANDEYARA   58             3               1            2   
2   3     CARICIA   29             2               1            3   
3   4     ADVANIA   17             2               2            4   
4   5      FLAINE   69             1               0            3   

   COAGULATION  HEPATIC  RENAL  ICC  ECOG  SCORE_SOFA  SCORE_FRAGILITY  \
0            3        2      1    2     2          11                2   
1            4        0      2    2     4          12                4   
2            1        2      3    2     2          12                2   
3            3        4      1    4     2          16                2   
4            2        1      2    2     2           9                2   

   CALCULATE_TOTAL  
0                3  
1                5  
2                4  
3                8  
4                4

In [105]:
df.describe()


ID          AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  \
count  1000.000000  1000.000000   1000.000000     1000.000000  1000.000000   
mean    500.500000    53.945000      2.076000        1.954000     1.974000   
std     288.819436    24.693476      1.387137        1.404941     1.425256   
min       1.000000    10.000000      0.000000        0.000000     0.000000   
25%     250.750000    32.000000      1.000000        1.000000     1.000000   
50%     500.500000    55.000000      2.000000        2.000000     2.000000   
75%     750.250000    76.000000      3.000000        3.000000     3.000000   
max    1000.000000    95.000000      4.000000        4.000000     4.000000   

       COAGULATION      HEPATIC        RENAL          ICC         ECOG  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      2.039000     1.987000     1.983000     3.022000     3.058000   
std       1.362841     1.423678     1.390196     1.000258     0.998816   
min       0.000000     0.000000     0.000000     2.000000     2.000000   
25%       1.000000     1.000000     1.000000     2.000000     2.000000   
50%       2.000000     2.000000     2.000000     4.000000     4.000000   
75%       3.000000     3.000000     3.000000     4.000000     4.000000   
max       4.000000     4.000000     4.000000     4.000000     4.000000   

        SCORE_SOFA  SCORE_FRAGILITY  CALCULATE_TOTAL  
count  1000.000000      1000.000000      1000.000000  
mean     12.013000         3.058000         6.184000  
std       3.416212         0.998816         2.100132  
min       2.000000         2.000000         2.000000  
25%      10.000000         2.000000         5.000000  
50%      12.000000         4.000000         6.000000  
75%      14.000000         4.000000         8.000000  
max      22.000000         4.000000        11.000000

In [106]:
df['AGE'].value_counts()

61    20
52    20
63    19
59    18
31    17
      ..
34     6
71     6
69     6
45     5
16     5
Name: AGE, Length: 86, dtype: int64

In [107]:
# Shape of Data
df.shape

(1000, 14)

In [108]:
# drop some colums we donot need like dates and id
df.drop(columns={'ID'},axis=1,inplace=True)
df.shape

(1000, 13)

In [109]:
df.shape

(1000, 13)

In [110]:
df['NEUROLOGICAL'].value_counts()

2    209
3    209
4    207
1    203
0    172
Name: NEUROLOGICAL, dtype: int64

In [111]:
df['CARDIOVASCULAR'].value_counts()

1    217
0    201
2    199
3    193
4    190
Name: CARDIOVASCULAR, dtype: int64

In [112]:
df['RESPIRATORY'].value_counts()

0    210
2    203
4    201
1    197
3    189
Name: RESPIRATORY, dtype: int64

In [113]:
df['COAGULATION'].value_counts()

3    235
2    208
1    202
4    179
0    176
Name: COAGULATION, dtype: int64

In [114]:
df['HEPATIC'].value_counts()

4    206
1    204
0    203
2    202
3    185
Name: HEPATIC, dtype: int64

In [115]:
df['RENAL'].value_counts()

3    213
2    209
1    198
0    198
4    182
Name: RENAL, dtype: int64

In [116]:
df['ICC'].value_counts()


4    511
2    489
Name: ICC, dtype: int64

In [117]:
df['ECOG'].value_counts()

4    529
2    471
Name: ECOG, dtype: int64

In [118]:
df['SCORE_SOFA'].value_counts()

12    121
11    119
13    103
10     98
14     91
15     83
9      75
8      63
16     53
7      48
17     46
6      23
18     22
19     15
5      13
20      8
21      6
4       5
3       3
22      3
2       2
Name: SCORE_SOFA, dtype: int64

In [119]:
df['SCORE_FRAGILITY'].value_counts()

4    529
2    471
Name: SCORE_FRAGILITY, dtype: int64

In [120]:
# CHECK  NULL Values
df.isnull().sum()

PATIENT            0
AGE                0
NEUROLOGICAL       0
CARDIOVASCULAR     0
RESPIRATORY        0
COAGULATION        0
HEPATIC            0
RENAL              0
ICC                0
ECOG               0
SCORE_SOFA         0
SCORE_FRAGILITY    0
CALCULATE_TOTAL    0
dtype: int64

In [121]:
df['CALCULATE_TOTAL'].value_counts()

7     176
5     165
6     149
8     139
4     116
3      83
9      78
10     49
2      31
11     14
Name: CALCULATE_TOTAL, dtype: int64

In [122]:
X = df[['AGE', 'NEUROLOGICAL', 'CARDIOVASCULAR',	'RESPIRATORY', 'COAGULATION', 'HEPATIC', 'RENAL', 'ICC', 'ECOG', 'SCORE_SOFA',	'SCORE_FRAGILITY']]
print(X)

     AGE  NEUROLOGICAL  CARDIOVASCULAR  RESPIRATORY  COAGULATION  HEPATIC  \
0     14             2               2            1            3        2   
1     58             3               1            2            4        0   
2     29             2               1            3            1        2   
3     17             2               2            4            3        4   
4     69             1               0            3            2        1   
..   ...           ...             ...          ...          ...      ...   
995   68             1               4            2            3        1   
996   83             0               0            2            0        4   
997   31             1               1            3            0        4   
998   91             2               3            4            3        3   
999   74             0               3            0            0        0   

     RENAL  ICC  ECOG  SCORE_SOFA  SCORE_FRAGILITY  
0        1    2     2 

In [123]:
df.shape

(1000, 13)

In [124]:
df['CALCULATE_TOTAL'].replace([1,2,3],[1,0,2],inplace=True)
df['CALCULATE_TOTAL'].value_counts().to_frame()

CALCULATE_TOTAL
7               176
5               165
6               149
8               139
4               116
2                83
9                78
10               49
0                31
11               14

In [125]:

y = df['CALCULATE_TOTAL']
print(y)
y.shape

0       2
1       5
2       4
3       8
4       4
       ..
995     7
996     5
997     6
998    11
999     4
Name: CALCULATE_TOTAL, Length: 1000, dtype: int64


(1000,)

In [126]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [127]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [128]:
# instance of model
treeModel = DecisionTreeClassifier()

In [129]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [130]:
predTree = treeModel.predict(x_test)

In [131]:
print(predTree)

[11  9  8 10 10  8  5  8  8  9  5  6  8  8  5  9  8  5  7  6  7  6  7  7
  4  8  2  7 10  9  6 10  7  6  4  5  7  7  6  4  7  5  7  5  7  5  6  6
 11  7  0  6  6 10  4  5  6  5  9  5  7  5  7  6  5  5  7  7  0  8  6 11
  5  6  8  2  6  2 10  8  6  8  8 10  8 11  6  6  6  5  2  8  8  4  2  5
  5  6  5  5  2  8  6  5 11  7  2  7  7  8  4  4  5 10  5  2  8  6  9  8
  5  4  8  4  5  5  8  7  7  8  5  6  7  4  6  5  6  5  6  6  8  0  6  0
  2  6  7  5  7  6  6  4  4  0  9  2  7  8  4  9  4  7  5  4  0  6  8  4
  4  8  5  6  7  6  2  0  7  4  9  5  7  6  5  5  4  8  7  5  4 10  5  7
  7  5  7  2  2  6  7  7]


In [132]:
from sklearn.metrics import accuracy_score

In [133]:
score = accuracy_score(y_test, predTree)

In [134]:
print(score)

0.99


In [135]:
from sklearn.ensemble import RandomForestClassifier

In [136]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [137]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [138]:
ranForestPred = ranModel.predict(x_test)

In [139]:
ranForestPred

array([11,  9,  8, 10, 10,  8,  5,  8,  8,  9,  5,  6,  8,  8,  5,  9,  8,
        5,  7,  6,  7,  6,  7,  7,  4,  8,  2,  7, 10,  9,  6, 10,  6,  6,
        4,  5,  7,  7,  6,  4,  7,  5,  7,  5,  7,  5,  6,  6, 11,  7,  0,
        6,  6, 10,  4,  5,  6,  5,  9,  5,  7,  5,  7,  6,  5,  5,  7,  7,
        0,  8,  6, 11,  5,  6,  8,  2,  6,  2, 10,  8,  6,  8,  8, 10,  8,
       11,  6,  6,  6,  5,  2,  8,  8,  4,  2,  5,  5,  6,  5,  5,  2,  8,
        6,  5, 11,  7,  2,  7,  7,  8,  4,  4,  5, 10,  5,  2,  8,  6,  9,
        8,  5,  4,  8,  4,  5,  5,  8,  7,  7,  8,  5,  6,  7,  4,  6,  5,
        6,  5,  6,  6,  8,  0,  6,  0,  2,  6,  7,  5,  7,  6,  6,  4,  4,
        0,  9,  2,  7,  7,  4,  9,  4,  7,  5,  4,  0,  6,  8,  4,  4,  8,
        5,  6,  7,  6,  2,  0,  7,  4,  9,  5,  7,  6,  5,  5,  4,  8,  7,
        5,  4, 10,  5,  7,  7,  5,  7,  2,  2,  6,  7,  7], dtype=int64)

In [140]:
ranModel.score(x_test, y_test)

1.0

In [141]:
ranModel

RandomForestClassifier(n_estimators=200)

In [142]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

1.0

In [143]:
pd.to_pickle(ranModel, 'Model_MDS.pickle')

In [144]:
model = pd.read_pickle('Model_MDS.pickle')

In [145]:
result = model.predict([[54, 4, 4, 2, 4, 1, 1, 4, 4, 29, 4]])
result

d:\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([9], dtype=int64)

In [146]:
result

array([9], dtype=int64)

In [147]:
#import pickle as plk

In [148]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [149]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)